const malla = {
  "1° Semestre": [
    { nombre: "Álgebra y Trigonometría", cod: "M01", requisitos: [] },
    { nombre: "Cálculo Diferencial", cod: "M02", requisitos: [] },
    { nombre: "Química General", cod: "M03", requisitos: [] },
    { nombre: "Introducción a la Ingeniería Industrial", cod: "M04", requisitos: [] },
    { nombre: "Formación Integral I", cod: "M05", requisitos: [] },
    { nombre: "Formación Integral II", cod: "M06", requisitos: [] },
  ],
  "2° Semestre": [
    { nombre: "Álgebra Lineal", cod: "M07", requisitos: ["M01"] },
    { nombre: "Cálculo Integral", cod: "M08", requisitos: ["M02"] },
    { nombre: "Física Mecánica", cod: "M09", requisitos: [] },
    { nombre: "Software para Ingeniería Industrial", cod: "M10", requisitos: ["M04"] },
    { nombre: "Formación Extra I", cod: "M11", requisitos: [] },
    { nombre: "Taller de Emprendimiento", cod: "M12", requisitos: [] },
  ],
  "3° Semestre": [
    { nombre: "Cálculo Multivariable", cod: "M13", requisitos: ["M08"] },
    { nombre: "Estadística", cod: "M14", requisitos: ["M08"] },
    { nombre: "Electromagnetismo", cod: "M15", requisitos: ["M02"] },
    { nombre: "Algoritmos y Programación", cod: "M16", requisitos: ["M10"] },
    { nombre: "Formación Extra II", cod: "M17", requisitos: [] },
    { nombre: "Inglés Básico", cod: "M18", requisitos: [] },
  ],
  "4° Semestre": [
    { nombre: "Ecuaciones Diferenciales", cod: "M19", requisitos: ["M07", "M08"] },
    { nombre: "Teoría de Sistemas", cod: "M20", requisitos: ["M12"] },
    { nombre: "Contabilidad y Costos", cod: "M21", requisitos: [] },
    { nombre: "Electrotecnia", cod: "M22", requisitos: ["M15"] },
    { nombre: "Termodinámica", cod: "M23", requisitos: [] },
    { nombre: "Inglés Intermedio", cod: "M24", requisitos: ["M18"] },
    { nombre: "Taller de Ciencias Básicas", cod: "M25", requisitos: [] },
  ],
  "5° Semestre": [
    { nombre: "Métodos de Producción", cod: "M26", requisitos: ["M14"] },
    { nombre: "Gestión Estratégica", cod: "M27", requisitos: ["M20"] },
    { nombre: "Microeconomía", cod: "M28", requisitos: ["M22"] },
    { nombre: "Mecánica de Sólidos y Fluidos", cod: "M29", requisitos: ["M26"] },
    { nombre: "Inferencia Estadística", cod: "M30", requisitos: ["M14"] },
    { nombre: "Inglés Avanzado", cod: "M31", requisitos: ["M24"] },
  ],
  "6° Semestre": [
    { nombre: "Modelamiento de Sistemas Informáticos", cod: "M32", requisitos: ["M19"] },
    { nombre: "Comportamiento Organizacional", cod: "M33", requisitos: ["M21"] },
    { nombre: "Optimización Lineal", cod: "M34", requisitos: [] },
    { nombre: "Finanzas", cod: "M35", requisitos: ["M22"] },
    { nombre: "Electivo Profesional 1", cod: "M36", requisitos: [] },
    { nombre: "Formación Integral III", cod: "M37", requisitos: [] },
    { nombre: "Taller de Ciencias de la Ingeniería", cod: "M38", requisitos: ["M27"] },
  ],
  "7° Semestre": [
    { nombre: "Gestión de Operaciones", cod: "M39", requisitos: ["M31"] },
    { nombre: "Gestión de Servicios", cod: "M40", requisitos: ["M21"] },
    { nombre: "Optimización No Lineal", cod: "M41", requisitos: ["M33"] },
    { nombre: "Evaluación de Proyectos", cod: "M42", requisitos: ["M23"] },
    { nombre: "Electivo Profesional 2", cod: "M43", requisitos: [] },
    { nombre: "Gestión de Calidad", cod: "M44", requisitos: ["M25"] },
    { nombre: "Práctica Profesional 1", cod: "M45", requisitos: [] },
  ],
  "8° Semestre": [
    { nombre: "Econometría", cod: "M46", requisitos: ["M25"] },
    { nombre: "Gestión de la Innovación", cod: "M47", requisitos: ["M21"] },
    { nombre: "Marketing", cod: "M48", requisitos: ["M25"] },
    { nombre: "Electivo Profesional 3", cod: "M49", requisitos: [] },
    { nombre: "Formación Integral IV", cod: "M50", requisitos: [] },
    { nombre: "Taller de Sistemas Productivos", cod: "M51", requisitos: ["M36"] },
  ],
  "9° Semestre": [
    { nombre: "Legislación Laboral y Ambiental", cod: "M52", requisitos: [] },
    { nombre: "Logística Integral", cod: "M53", requisitos: ["M37"] },
    { nombre: "Simulación de Procesos", cod: "M54", requisitos: ["M35"] },
    { nombre: "Formulación y Preparación de Proyectos", cod: "M55", requisitos: ["M34"] },
    { nombre: "Electivo Profesional 4", cod: "M56", requisitos: [] },
    { nombre: "Taller de Proyecto de Emprendimiento", cod: "M57", requisitos: ["M45"] },
    { nombre: "Práctica Profesional 2", cod: "M58", requisitos: [] },
  ],
  "10° Semestre": [
    { nombre: "Inclusión al Ambiente Laboral", cod: "M59", requisitos: [] },
    { nombre: "Seminario de Titulación", cod: "M60", requisitos: [] },
    { nombre: "Electivo Profesional 5", cod: "M61", requisitos: [] },
    { nombre: "Formación Integral V", cod: "M62", requisitos: [] },
  ],
};